# 应用配置
app:
  name: Gypsophila AI Backend
  env: test
  port: 3000
  url: http://test-api.gypsophila-ai.com
  prefix: /api

# 数据库配置
database:
  type: mysql
  host: localhost
  port: 3306
  username: test_user
  password: test_password
  database: gypsophila_test
  synchronize: true
  logging: true

# JWT配置
jwt:
  secret: your-test-jwt-secret-key
  expiresIn: 15m
  refreshExpiresIn: 7d

# 日志配置
logger:
  level: debug
  maxFiles: 10
  maxSize: 10485760 # 10MB

# CORS配置
cors:
  enabled: true
  origin: http://test.gypsophila-ai.com
  methods: GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS
  credentials: true

# 安全配置
security:
  rateLimiter:
    enabled: true
    windowMs: 60000 # 1分钟
    max: 200 # 测试环境允许更多请求
  helmet:
    enabled: true
  compression:
    enabled: true 