# 应用配置
app:
  name: Gypsophila AI Backend
  env: development
  port: 3000
  prefix: /api

# 数据库配置
database:
  type: mysql
  host: localhost
  port: 3306
  username: 'root'
  password: 'j!Y6hTwR'
  database: 'gypsophila-ai'
  synchronize: true
  logging: true

# Redis配置
redis:
  host: localhost
  port: 6379
  password: ''
  db: 0
  keyPrefix: ''
# JWT配置
jwt:
  secret: j+v22~tXkFPcYG*r5%Qi.4fRM(EAFF!G
  expiresIn: 1d
  refreshExpiresIn: 7d

# 日志配置
logger:
  level: debug
  console: true   # 控制日志是否直接输出在控制台上
  file:
    enabled: false # 控制日志是否采用文件方式记录
    maxFiles: 30
    maxSize: 10485760 # 10MB

# CORS配置
cors:
  enabled: true
  origin: '*'
  methods: GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS
  credentials: true

# 安全配置
security:
  rateLimiter:
    enabled: true
    windowMs: 60000 # 1分钟
    max: 100 # 每分钟最多100次请求
  helmet:
    enabled: true
  compression:
    enabled: true 