# 应用配置
app:
  name: Gypsophila AI Backend
  env: development
  port: 'adsfkhadjh'
  url: http://localhost:3000
  prefix: /api

# 数据库配置
database:
  type: mysql
  host: localhost
  port: 3306
  username: root
  password: password
  database: gypsophila
  synchronize: true
  logging: true

# JWT配置
jwt:
  secret: your-jwt-secret-key
  expiresIn: 15m
  refreshExpiresIn: 7d

# 日志配置
logger:
  level: debug
  maxFiles: 30
  maxSize: 10485760 # 10MB

# CORS配置
cors:
  enabled: true
  origin: '*'
  methods: GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS
  credentials: true

# 安全配置
security:
  rateLimiter:
    enabled: true
    windowMs: 60000 # 1分钟
    max: 100 # 每分钟最多100次请求
  helmet:
    enabled: true
  compression:
    enabled: true 